Use a python venv for tests
Currently all tests are failing with:

```
python3 -m pip install duffy fabric httpx
```

and

```
Installing collected packages: pyxdg, wrapt, typing-extensions, sniffio, pycparser, invoke, h11, greenlet, decorator, annotated-types, typing-inspection, pydantic-core, httpcore, deprecated, cffi, anyio, pynacl, pydantic, httpx, paramiko, duffy, fabric
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.10.0
ERROR: Cannot uninstall typing_extensions 4.10.0, RECORD file not found. Hint: The package was installed by debian.
```

Switch to using a python virtual environment to avoid conflicts with
installed packages.